AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys Kaytu Platform to AWS Organization
Parameters:
  IAMUsernameInAWSAccount:
    Type: String
    Default: SimpleStackIAMUser
    Description: IAM User to create
  IAMGroupnameInAWSAccount:
    Type: String
    Default: SimpleStackIAMGroup
    Description: IAM User to create
  RoleNameInAccount:
    Type: String
    Default: SimpleStackReadOnly
    Description: The name of the role that will be assumed in each member account.


Resources:
  AWSAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleNameInAccount
      Description: Allows the platform to gather inventory of the organization and member accounts
      Policies:
        - PolicyName: SimpleStackRoleAssumption
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: '*'
                Action:
                  - 'organizations:List*'
                  - 'sts:AssumeRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}' 
            Action:
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      ManagedPolicyArns:
          - arn:aws:iam::aws:policy/SecurityAudit
          - arn:aws:iam::aws:policy/ReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
          - arn:aws:iam::aws:policy/AWSSSODirectoryReadOnly
          - arn:aws:iam::aws:policy/AWSSSOReadOnly
          - arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly
          - arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess
  IAMGroupInAWSAccount:
   Type: 'AWS::IAM::Group'
   Properties:
     GroupName: !Ref IAMGroupnameInAWSAccount
  AddOrganizationUserToOrganizationGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
     Users:
      - !Ref IAMUserInAWSAccount
     GroupName: !Ref IAMGroupInAWSAccount
  AttachRoleToOrganizationGroup:
      Type: 'AWS::IAM::GroupPolicy'
      Properties:
        PolicyName: SimpleStackAllowRoleAssumption
        GroupName: !Ref IAMGroupInAWSAccount
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 'sts:AssumeRole'
              Resource: !GetAtt AWSAccountRole.Arn
  

Outputs:
  CFNAWSAccountRoleArn:
    Description: Organization Role.
    Value: !GetAtt AWSAccountRole.Arn
    